variables:
  STMGR_VERSION: latest

stages:
  - build
  - boot

build-example:
  stage: build
  image: debian:bookworm
  before_script:
    - apt-get -qq update
    - apt-get install -qqy curl git golang-1.19-go pigz
    - apt-get install -qqy sudo make mmdebstrap cpio
    - |
      export GOPATH="${PWD}"/.go
      export PATH="${PATH}":/usr/lib/go-1.19/bin:"${GOPATH}"/bin
      go install system-transparency.org/stmgr@"${STMGR_VERSION}"
  script:
    - echo stimages > config/example/pw.root
    - make stimage
  artifacts:
    paths:
      - build/stimage.*
      - build/stboot.iso

boot-example:
  stage: boot
  image: debian:bookworm
  before_script:
    - apt-get -qq update
    - apt-get install -qqy ncat qemu-system-x86
  script:
    - test/boot.sh
