stages:
  - build

make-default:
  stage: build
  image: debian:bookworm-slim
  before_script:
    - apt-get update -qq
    - apt-get install -qqy curl git golang-1.19-go pigz sudo make mmdebstrap cpio
    - export GOPATH="${PWD}"/.go
    - export PATH="${PATH}":/usr/lib/go-1.19/bin:"${GOPATH}"/bin
    - go install system-transparency.org/stmgr@latest
  script:
    - echo stimages > config/example/pw.root
    - make
  artifacts:
    paths:
      - build/stimage.*
