#! /bin/bash
set -eu

# Run a command in a container defined by $CONTAINERFILE.
# If first argument is -r, refresh the image first.

IMAGE_NAME=stimage
CONTAINERFILE=debian13-slim.container
VOLUME_MOUNT_OPTS=		# Use :z for SELinux relabeling

[ -f /etc/fedora-release ] && VOLUME_MOUNT_OPTS+=:z

refresh_deps() {
    CF="$1"
    while read -r _ img; do
	podman pull "$img"
    done < <(grep ^FROM "$CF")
}

# Refresh images we depend upon
if [ "$1" = "-r" ]; then
    shift
    refresh_deps "$CONTAINERFILE"
fi

# Build image
podman build -q -t "$IMAGE_NAME" -f "$CONTAINERFILE"

# Run image in new container with current directory mounted on /c
podman run --rm --volume "${PWD}:/c${VOLUME_MOUNT_OPTS}" "$IMAGE_NAME" $@
