#! /bin/sh
set -eu

# This script is run by st-init-network.service after /stdata has been
# mounted but before networking has been started.

if [ -r /stdata/etc/resolv.conf ]; then
    cp /stdata/etc/resolv.conf /etc/resolv.conf
fi

if [ -d /stdata/etc/systemd/network ];then
    mkdir -p /etc/systemd/network
    cp /stdata/etc/systemd/network/*.netdev /etc/systemd/network/ || true
    cp /stdata/etc/systemd/network/*.network /etc/systemd/network/ || true
fi
